name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      
    defaults:
      run:
        shell: bash

    steps:
      - name: Create tfvars file
        run: |
          cat > terraform.tfvars << EOF
          folder_id = "${{ secrets.TF_VAR_folder_id }}"
          cloud_id = "${{ secrets.TF_VAR_cloud_id }}"
          EOF
    
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
  
      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}"
  
      - name: Terraform Format
        run: terraform fmt -check
  
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        env:
          TF_VAR_folder_id: ${{ secrets.TF_VAR_folder_id }}
          TF_VAR_cloud_id: ${{ secrets.TF_VAR_cloud_id }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
  
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
          retention-days: 1

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: 
      name: production
    if: github.ref == 'refs/heads/master'
    
    env:
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
  
      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          
      - name: Terraform Init
        run: |
          terraform init \
          -backend-config="access_key=${{ secrets.S3_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.S3_SECRET_KEY }}"
  
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false tfplan
        env:
          TF_VAR_folder_id: ${{ secrets.TF_VAR_folder_id }}
          TF_VAR_cloud_id: ${{ secrets.TF_VAR_cloud_id }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

