name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
  
      - name: Create tfvars file
        run: |
          cat > terraform.tfvars << EOF
          folder_id = "${{ secrets.TF_VAR_folder_id }}"
          cloud_id = "${{ secrets.TF_VAR_cloud_id }}"
          EOF
        shell: bash

      - name: Terraform Init
        run: terraform init
        continue-on-error: true

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        env:
          TF_VAR_folder_id: ${{ secrets.TF_VAR_folder_id }}
          TF_VAR_cloud_id: ${{ secrets.TF_VAR_cloud_id }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        continue-on-error: true

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform destroy -auto-approve -input=false tfplan
        env:
          TF_VAR_folder_id: ${{ secrets.TF_VAR_folder_id }}
          TF_VAR_cloud_id: ${{ secrets.TF_VAR_cloud_id }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      
